### ISSUE TITLE
Number of gold and predicted relations

### ISSUE THREAD

**Issue by donovanOng** [shizhouxing/DialogueDiscourseParsing#10]
Thanks for releasing the code.

I will like to ask a few questions:

1. Why did you add the number of EDUs without a parent to the total number of gold relations?
2. Why did you increase the number of correct relations when the first EDU does not have any parent?

From [https://github.com/shizhouxing/DialogueDiscourseParsing/blob/master/Model.py](https://github.com/shizhouxing/DialogueDiscourseParsing/blob/master/Model.py )
```python
for dialog in batch:
    cnt = [0] * len(dialog["edus"])
    for r in dialog["relations"]:
        cnt[r["y"]] += 1
    for i in range(len(dialog["edus"])):
        if cnt[i] == 0:
            cnt_golden += 1
    cnt_pred += 1
    if cnt[0] == 0:
        cnt_cor_bi += 1
        cnt_cor_multi += 1
```

**Comment by shizhouxing** [comment]
Hi @donovanOng ,

1. Such EDUs are considered to be linked with the dummy root and thus we add the number of total relations. This follows the evaluation in the STAC work.

2. Our model always (implicitly) predicts that the parent of the first EDU is the dummy root, and it does not link any other EDU to the dummy root. Relations linked to the dummy root are not contained in `dialog["relations"]`, but they can be inferred according to whether each EDU has a non-dummy parent. So we handle the dummy root with some extra lines of code. In the ground truth, if the first EDU does not have any incoming edge, then its ground-truth parent is the dummy root and in this case our prediction is correct.

**Comment by donovanOng** [comment]
Thanks for the prompt and detailed response.

Are these two evaluation strategies also used to compute the evaluation score for the baseline models?

Seems that for ILP, Line 366-377 [https://github.com/shizhouxing/DialogueDiscourseParsing/blob/master/baseline/main.py](https://github.com/shizhouxing/DialogueDiscourseParsing/blob/master/baseline/main.py )

- The gold relations did not include the extra relations between the dummy root with no-parent EDUs.
- And similarly, the relations between the first EDU and dummy root was not added to the correctly predicted relations.

Please let me know if I misunderstood the code. 

I will like to make a fair comparison of your model. Thank you.

```python
for relation in dialog["relations"]:
    relation_types[relation["x"]][relation["y"]] = relation["type"] + 1
    cnt_golden += 1

pred = load_scip_output(dialog, output_path)
for r in pred:
    cnt_pred += 1
    if relation_types[r[0]][r[1]] > 0:
        cnt_cor_bi += 1
        if r[2] == relation_types[r[0]][r[1]] - 1:
            cnt_cor_multi += 1
```

**Comment by shizhouxing** [comment]
@donovanOng Sorry for the confusion. For ILP, I think we have already added the dummy root directly to the dialogue when loading the data, to call the ILP solver more conveniently. See https://github.com/shizhouxing/DialogueDiscourseParsing/blob/master/baseline/utils.py#L70.

**Comment by donovanOng** [comment]
Thanks for pointing it out! Sorry for missing that!

Any plan to release trained models and updated result based on the new training data?

**Comment by shizhouxing** [comment]
Yes I think I can try to release a checkpoint as also requested in issue #9 . Thanks for the suggestion!

**Comment by donovanOng** [comment]
Thank you!
