### ISSUE TITLE
Direction of relations

### ISSUE THREAD

**Issue by chijames** [shizhouxing/DialogueDiscourseParsing#11]
Hi,

I notice that there are some backward relations in the data. However, it seems to me that the model does not care about directions. So if a relation is 5(x)=>4(y), and the model predicts (4,5), is this considered as a correct prediction?

Thanks.

**Comment by shizhouxing** [comment]
That's an incorrect prediction. Our model only predicts forward relations
and gives up on backward relations (the proportion of backward relations is
relatively low).

**Comment by chijames** [comment]
Ok. I am trying to ensure my evaluation process runs like yours. So to summarize, I can directly retrieve the relations in test data , increment them by 1 (ex [4,5] => [5,6]), connect all dangling edus_{idx} to 0 [0,idx+1], and augment the golden set with a [0, 1] to account for dummy root predictions. In addition, all the directions should be considered for correctness.

Is the above process correct? Or did I miss anything? Thanks!

**Comment by shizhouxing** [comment]
@chijames I think there is no need to additionally add [0, 1] to the ground truth? For dummy root links, I think you only need to link the root to nodes without any incoming relation.

**Comment by chijames** [comment]
Ok, so basically it is included in the "connect all dangling edus_{idx}" step. Since the first edu(node) does not have any incoming relation either, correct?

**Comment by shizhouxing** [comment]
>so basically it is included in the "connect all dangling edus_{idx}" step.

Yes I think that's correct.

>the first edu(node) does not have any incoming relation either

But I think this may not be guaranteed. I am not sure if it can have some backward relation coming from a later EDU. I think it's allowed but I'm not sure if it exists in the dataset.

**Comment by chijames** [comment]
So I checked the test set and found out that this is true (no backward links point to the first edu). One final question: if we create "pseudo" relations by connecting the dummy root to edus without any incoming relation, is their direction {"x":0, "y":dangling_edu}? Also, how about their relation types (None)?

Thanks!

**Comment by shizhouxing** [comment]
>is their direction {"x":0, "y":dangling_edu}?

Yes.

>Also, how about their relation types (None)?

It can just be a special type different from the existing relations.

**Comment by chijames** [comment]
So let's say we add an additional type (_special_). If the model predicts the existence of a pseudo link and its type as _special_, it's a correct count, otherwise an incorrect count (for link & Rel setting).

**Comment by shizhouxing** [comment]
Yes, sounds right. But our model always only predicts 0->1 for dummy root
relation (other EDUs are guaranteed to be linked to an actual EDU in our
prediction).
