### ISSUE TITLE
The purpose of using turn as a feature

### ISSUE THREAD

**Issue by chijames** [shizhouxing/DialogueDiscourseParsing#12]
Hi,

I notice that the model uses "turn" information as part of the feature vector: https://github.com/shizhouxing/DialogueDiscourseParsing/blob/master/Model.py#L338. However, I cannot find relevant discussion in the paper (apology if it's somewhere and I miss it). Could you please shed some light on this design choice?

Thanks!

**Comment by shizhouxing** [comment]
Hi @chijames , these are not so important and according to my experiments they do not quite make a difference. Previously I just added some manual features that I thought might improve the prediction. The "turn" information indicates whether the two EDUs belong to the same turn, i.e., whether there is no EDU by other speakers between these two EDUs.
