### ISSUE TITLE
Link prediction estimates

### ISSUE THREAD

**Issue by jetwu-create** [shizhouxing/DialogueDiscourseParsing#13]
Dear, thank you for opening resource!
But when i reproduce it, one question puzzles me. This is the link prediction part, i can not find the position of link prediction estimates in your code. Link prediction estimates a distribution over its preceding EDUs. Could you give me a cue? Thanks!

**Comment by shizhouxing** [comment]
Hello @jetwu-create ,  link prediction is at:
https://github.com/shizhouxing/DialogueDiscourseParsing/blob/master/Agent.py#L132

`is_multi` indicates whether we want to predict the relation type (True) or only the link existence (False).

Sorry that the naming in the code may be confusing as we previously tried an RL-like method. 

Please let me know if this resolves your question.

**Comment by jetwu-create** [comment]
Thank you for your response! I can find and understand it, your work is very nice!
