### ISSUE TITLE
Code pytorch version

### ISSUE THREAD

**Issue by Chucy2020** [shizhouxing/DialogueDiscourseParsing#14]
hello, nowadays, pytorch is used by very many people, have you considered providing the code for the pytorch version?

**Comment by shizhouxing** [comment]
Hi @Chucy2020 , I’m no longer working in this area so I don’t plan to have a PyTorch version by myself.

**Comment by Chucy2020** [comment]
> hello, nowadays, pytorch is used by very many people, have you considered providing the code for the pytorch version?

Ok, I understand, thank you very much for your excellent work.

**Comment by Chucy2020** [comment]
> Hi @Chucy2020 , I’m no longer working in this area so I don’t plan to have a PyTorch version by myself.

Ok, I understand, thank you very much for your excellent work.
