### ISSUE TITLE
The test set sharing link has expired

### ISSUE THREAD

**Issue by loginaway** [shizhouxing/DialogueDiscourseParsing#15]
Hi,

It seems that the test set you shared at

> We share the [test data we used](https://drive.google.com/file/d/1KmTw_DbJawNfl6asqtRnG_f4BwXtl4b7/view?usp=sharing) from the 2018-03-21 version.

is down. Would you mind updating this link? Thank you!

**Comment by shizhouxing** [comment]
Hi @loginaway , thanks for letting me know, and I have replaced the link in README.
