### ISSUE TITLE
感觉代码和论文对不上啊

### ISSUE THREAD

**Issue by 1160300929** [shizhouxing/DialogueDiscourseParsing#2]
代码中出现的policy network是什么呀？还有bi encoder和multi encoder是什么啊

**Comment by shizhouxing** [comment]
Hi, the "policy network" stands for networks for link prediction and relation classification.
"bi encoder" and "multi encoder" are used to encode representations for link prediction and relation classification respectively. 
Sorry for the confusion in naming.
