### ISSUE TITLE
Questions about the STAC dataset

### ISSUE THREAD

**Issue by pqpq17** [shizhouxing/DialogueDiscourseParsing#5]
Hi! Thank you for opening resource!

But I got some confusions about the dataset.
In other issue you said that you use the linguistic version data,
but when I donwload the dataset I found that only situated version has TEST set,
and linguistic version hasn't.

It confuse me.
Or could you please send your dataset for me?
my email is scut_pq@163.com
Thanks a lot!

**Comment by shizhouxing** [comment]
Dataset sent.

This is because that STAC's website seems to be often updated and the
dataset currently available on the website is newer and different from the
version we used.
